### ISSUE TITLE
reference app not available / docs error

### ISSUE THREAD

**Issue by ranshe** [ARMmbed/reference-design-RD1622#1]
In https://github.com/ARMmbed/reference-design-RD1622/blob/master/Documentation/RD1622_README.md, we ask the user to "mbed import https://github.com/ARMmbed/reference-design-RD1622.git" - this is the master reference design, and as such doesn't have the RD1622 subfolder which is called for in step 2.

Please fix

**Comment by ashok-rao** [comment]
Fixed by commit #ed4cdcd82253fe84ba .. @ranshe , please let me know if this fixes your issue..
